/**
 * Context Generation Service
 * Assembles CLAUDE.md content from graph data and repository summaries.
 */

import { db } from '../db';
import { repositorySummaries } from '../db/schema';
import { eq, desc } from 'drizzle-orm';
import type { GraphManager } from './graph/graph.service';

interface RepoInfo {
  id: string;
  slug: string;
  defaultBranch: string | null;
}

/**
 * Generate CLAUDE.md content from graph data and repository summaries.
 * Returns the markdown string, or null if no summary data is available.
 */
export async function generateClaudeMd(
  repo: RepoInfo,
  ownerSlug: string,
  repoSlug: string,
  graph: GraphManager
): Promise<string | null> {
  // Fetch latest repository summary
  const summary = await db.query.repositorySummaries.findFirst({
    where: eq(repositorySummaries.repositoryId, repo.id),
    orderBy: desc(repositorySummaries.createdAt),
  });

  if (!summary) {
    return null; // No AI summary available — skip
  }

  // Fetch graph stats
  let stats = { fileCount: 0, symbolCount: 0, commitCount: 0, moduleCount: 0, functionCount: 0, classCount: 0, relationshipCount: 0 };
  try {
    stats = await graph.getStats();
  } catch {
    // Graph might be empty
  }

  // Fetch top 15 files by complexity
  let topFiles: Array<{ path: string; linesOfCode: number; complexity: number; summary: string; language: string }> = [];
  try {
    const fileResults = await graph.query(
      `MATCH (f:File)
       WHERE f.complexity > 0
       RETURN f.path AS path, f.linesOfCode AS linesOfCode, f.complexity AS complexity,
              f.summary AS summary, f.language AS language
       ORDER BY f.complexity DESC
       LIMIT 15`
    );
    topFiles = fileResults.map((r: any) => ({
      path: r.path || '',
      linesOfCode: r.linesOfCode || 0,
      complexity: r.complexity || 0,
      summary: r.summary || '',
      language: r.language || '',
    }));
  } catch {
    // Graph query failed
  }

  // Fetch top 15 symbols by complexity
  let topSymbols: Array<{ qualifiedName: string; name: string; kind: string; file: string; complexity: number; summary: string }> = [];
  try {
    const symbolResults = await graph.query(
      `MATCH (s:Symbol)
       WHERE s.complexity > 0
       RETURN s.qualifiedName AS qualifiedName, s.name AS name, s.kind AS kind,
              s.file AS file, s.complexity AS complexity, s.summary AS summary
       ORDER BY s.complexity DESC
       LIMIT 15`
    );
    topSymbols = symbolResults.map((r: any) => ({
      qualifiedName: r.qualifiedName || '',
      name: r.name || '',
      kind: r.kind || '',
      file: r.file || '',
      complexity: r.complexity || 0,
      summary: r.summary || '',
    }));
  } catch {
    // Graph query failed
  }

  // Fetch module/directory structure
  let modules: Array<{ path: string; fileCount: number }> = [];
  try {
    const moduleResults = await graph.query(
      `MATCH (m:Module)-[:CONTAINS]->(f:File)
       WITH m.path AS path, count(f) AS fileCount
       WHERE NOT path CONTAINS '/'
       RETURN path, fileCount
       ORDER BY fileCount DESC
       LIMIT 20`
    );
    modules = moduleResults.map((r: any) => ({
      path: r.path || '',
      fileCount: typeof r.fileCount === 'number' ? r.fileCount : 0,
    }));
  } catch {
    // Graph query failed
  }

  // Fetch language breakdown from file nodes
  let languages: Array<{ language: string; count: number }> = [];
  try {
    const langResults = await graph.query(
      `MATCH (f:File)
       WHERE f.language IS NOT NULL AND f.language <> 'unknown'
       RETURN f.language AS language, count(f) AS count
       ORDER BY count DESC
       LIMIT 10`
    );
    languages = langResults.map((r: any) => ({
      language: r.language || '',
      count: typeof r.count === 'number' ? r.count : 0,
    }));
  } catch {
    // Graph query failed
  }

  // Assemble the markdown
  const lines: string[] = [];

  lines.push('# CLAUDE.md — Auto-generated by CV-Hub');
  lines.push('');
  lines.push('> This file is regenerated on each graph sync. Do not edit manually.');
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push(summary.summary);
  lines.push('');

  // Technologies
  const techs = (summary.technologies as string[] | null) || [];
  if (techs.length > 0) {
    lines.push('## Technologies');
    for (const tech of techs) {
      lines.push(`- ${tech}`);
    }
    lines.push('');
  }

  // Entry Points
  const entryPoints = (summary.entryPoints as string[] | null) || [];
  if (entryPoints.length > 0) {
    lines.push('## Entry Points');
    for (const ep of entryPoints) {
      lines.push(`- ${ep}`);
    }
    lines.push('');
  }

  // Architecture Patterns
  const patterns = (summary.keyPatterns as string[] | null) || [];
  if (patterns.length > 0) {
    lines.push('## Architecture Patterns');
    for (const p of patterns) {
      lines.push(`- ${p}`);
    }
    lines.push('');
  }

  // Repository Stats
  lines.push('## Repository Stats');
  lines.push(`- ${stats.fileCount} files, ${stats.symbolCount} symbols, ${stats.commitCount} commits`);
  if (languages.length > 0) {
    const langStr = languages.map(l => `${l.language} (${l.count})`).join(', ');
    lines.push(`- Languages: ${langStr}`);
  }
  lines.push('');

  // Key Files
  if (topFiles.length > 0) {
    lines.push('## Key Files (by complexity)');
    lines.push('| File | LOC | Complexity | Summary |');
    lines.push('|------|-----|------------|---------|');
    for (const f of topFiles) {
      const summaryText = f.summary ? f.summary.replace(/\|/g, '\\|').replace(/\n/g, ' ') : '';
      lines.push(`| ${f.path} | ${f.linesOfCode} | ${f.complexity} | ${summaryText} |`);
    }
    lines.push('');
  }

  // Key Symbols
  if (topSymbols.length > 0) {
    lines.push('## Key Symbols (by complexity)');
    lines.push('| Symbol | Kind | File | Complexity | Summary |');
    lines.push('|--------|------|------|------------|---------|');
    for (const s of topSymbols) {
      const summaryText = s.summary ? s.summary.replace(/\|/g, '\\|').replace(/\n/g, ' ') : '';
      lines.push(`| ${s.name} | ${s.kind} | ${s.file} | ${s.complexity} | ${summaryText} |`);
    }
    lines.push('');
  }

  // Directory Structure
  if (modules.length > 0) {
    lines.push('## Directory Structure');
    for (const m of modules) {
      lines.push(`- \`${m.path}/\` — ${m.fileCount} files`);
    }
    lines.push('');
  }

  // MCP Tools hints
  lines.push('## Using CV-Hub MCP Tools');
  lines.push('');
  lines.push('This repository is hosted on CV-Hub with knowledge graph and semantic search.');
  lines.push('Configure MCP access with: `cv auth setup cv-hub`');
  lines.push('');
  lines.push('Useful queries:');
  lines.push('- `search_code` — semantic code search across the repo');
  lines.push('- `get_symbol` — get details, callers, and callees for any function');
  lines.push('- `find_callers` / `find_callees` — trace call chains');
  lines.push('- `query_graph` — run custom Cypher queries against the knowledge graph');
  lines.push('- `complexity_hotspots` — find high-complexity code');
  lines.push('- `find_dead_code` — find unused functions');
  lines.push('- `get_repo_context` — get structured JSON context for this repo');
  lines.push('');

  return lines.join('\n');
}

/**
 * Get structured context data (JSON-friendly) for MCP tool responses.
 * Returns the same data as CLAUDE.md but as a structured object.
 */
export async function getStructuredContext(
  repo: RepoInfo,
  ownerSlug: string,
  repoSlug: string,
  graph: GraphManager
): Promise<{
  summary: string | null;
  technologies: string[];
  entryPoints: string[];
  keyPatterns: string[];
  stats: { fileCount: number; symbolCount: number; commitCount: number; moduleCount: number };
  topFiles: Array<{ path: string; linesOfCode: number; complexity: number; summary: string }>;
  topSymbols: Array<{ name: string; kind: string; file: string; complexity: number; summary: string }>;
  languages: Array<{ language: string; count: number }>;
  modules: Array<{ path: string; fileCount: number }>;
}> {
  // Fetch latest repository summary
  const summaryRecord = await db.query.repositorySummaries.findFirst({
    where: eq(repositorySummaries.repositoryId, repo.id),
    orderBy: desc(repositorySummaries.createdAt),
  });

  // Fetch graph stats
  let stats = { fileCount: 0, symbolCount: 0, commitCount: 0, moduleCount: 0, functionCount: 0, classCount: 0, relationshipCount: 0 };
  try {
    stats = await graph.getStats();
  } catch {
    // Graph might be empty
  }

  // Top files
  let topFiles: Array<{ path: string; linesOfCode: number; complexity: number; summary: string }> = [];
  try {
    const fileResults = await graph.query(
      `MATCH (f:File) WHERE f.complexity > 0
       RETURN f.path AS path, f.linesOfCode AS linesOfCode, f.complexity AS complexity, f.summary AS summary
       ORDER BY f.complexity DESC LIMIT 15`
    );
    topFiles = fileResults.map((r: any) => ({
      path: r.path || '',
      linesOfCode: r.linesOfCode || 0,
      complexity: r.complexity || 0,
      summary: r.summary || '',
    }));
  } catch { /* empty */ }

  // Top symbols
  let topSymbols: Array<{ name: string; kind: string; file: string; complexity: number; summary: string }> = [];
  try {
    const symbolResults = await graph.query(
      `MATCH (s:Symbol) WHERE s.complexity > 0
       RETURN s.name AS name, s.kind AS kind, s.file AS file, s.complexity AS complexity, s.summary AS summary
       ORDER BY s.complexity DESC LIMIT 15`
    );
    topSymbols = symbolResults.map((r: any) => ({
      name: r.name || '',
      kind: r.kind || '',
      file: r.file || '',
      complexity: r.complexity || 0,
      summary: r.summary || '',
    }));
  } catch { /* empty */ }

  // Languages
  let languages: Array<{ language: string; count: number }> = [];
  try {
    const langResults = await graph.query(
      `MATCH (f:File) WHERE f.language IS NOT NULL AND f.language <> 'unknown'
       RETURN f.language AS language, count(f) AS count ORDER BY count DESC LIMIT 10`
    );
    languages = langResults.map((r: any) => ({
      language: r.language || '',
      count: typeof r.count === 'number' ? r.count : 0,
    }));
  } catch { /* empty */ }

  // Modules
  let modules: Array<{ path: string; fileCount: number }> = [];
  try {
    const moduleResults = await graph.query(
      `MATCH (m:Module)-[:CONTAINS]->(f:File)
       WITH m.path AS path, count(f) AS fileCount
       WHERE NOT path CONTAINS '/'
       RETURN path, fileCount ORDER BY fileCount DESC LIMIT 20`
    );
    modules = moduleResults.map((r: any) => ({
      path: r.path || '',
      fileCount: typeof r.fileCount === 'number' ? r.fileCount : 0,
    }));
  } catch { /* empty */ }

  return {
    summary: summaryRecord?.summary || null,
    technologies: (summaryRecord?.technologies as string[] | null) || [],
    entryPoints: (summaryRecord?.entryPoints as string[] | null) || [],
    keyPatterns: (summaryRecord?.keyPatterns as string[] | null) || [],
    stats: {
      fileCount: stats.fileCount,
      symbolCount: stats.symbolCount,
      commitCount: stats.commitCount,
      moduleCount: stats.moduleCount,
    },
    topFiles,
    topSymbols,
    languages,
    modules,
  };
}
